---
name: Adacord CLI CI

on:
  pull_request:
    paths:
      - 'src/**'
  push:
    branches:
      - main

jobs:
  codeChecks:
    name: Check style and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: Load cached Poetry local folder
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: dev-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            dev-poetry-

      - name: Install CI dependencies
        run: poetry install --dev

      - name: Black code
        run: poetry run black --check cli tests

      - name: Check imports order
        run: poetry run isort -c cli tests

      - name: Flake8 code
        run: poetry run flake8 cli tests

      - name: Test code
        run: poetry run pytest -xv
