---
name: Publish to PYPI

on:
  pull_request:
    paths:
      - 'src/**'
  push:
    branches:
      - main

jobs:
  codeChecks:
    name: Check style and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: make install-base

      - name: Publish to pypy
        run: poetry publish --build -n -u __token__ -p {{ secrets.PYPI_TOKEN }}

